// ================================================
//  EXPLORATION BIOMIMÉTIQUE — data.js v2
//  Photos Unsplash libres de droits commerciaux
// ================================================

const BASE = "assets/";

const CARDS_DATA = [
  { id:1,  pairId:1,  type:"vivant",      name:"MARTIN-PÊCHEUR",            tagline:"Mon bec fend l'eau sans une ride.",
    photo: BASE + "card_1.png",
    explication:{ titre:"Martin-pêcheur & Shinkansen", texte:"L'ingénieur Eiji Nakatsu s'est inspiré du bec fuseau du martin-pêcheur pour redesigner le nez du Shinkansen. Résultat : fin du boom sonore dans les tunnels, −15 % de consommation d'énergie et +10 % de vitesse." }},
  { id:2,  pairId:1,  type:"application", name:"SHINKANSEN",                 tagline:"L'innovation par la forme.",
    photo: BASE + "card_2.png",
    explication:null },

  { id:3,  pairId:2,  type:"vivant",      name:"BALEINE À BOSSE",            tagline:"Mes nageoires bossélées fendent l'eau.",
    photo: BASE + "card_3.png",
    explication:{ titre:"Baleine à bosse & Éolienne Tuberculeuse", texte:"Les tubercules sur les nageoires de la baleine réduisent la traînée de 32 % et augmentent la portance. Appliqués aux pales d'éoliennes, ce principe augmente l'efficacité de 20 %." }},
  { id:4,  pairId:2,  type:"application", name:"ÉOLIENNE TUBERCULEUSE",      tagline:"Mes pales captent le vent avec plus de force.",
    photo: BASE + "card_4.png",
    explication:null },

  { id:5,  pairId:3,  type:"vivant",      name:"PEAU DE REQUIN",             tagline:"Mes micro-écailles réduisent la friction.",
    photo: BASE + "card_5.png",
    explication:{ titre:"Peau de requin & Combinaison Speedo", texte:"La peau du requin est couverte de micro-denticules qui réduisent la turbulence. Speedo s'en est inspiré pour créer le maillot Fastskin, réduisant la traînée de 4 %." }},
  { id:6,  pairId:3,  type:"application", name:"COMBINAISON SPEEDO",         tagline:"Je glisse comme un prédateur marin.",
    photo: BASE + "card_6.png",
    explication:null },

  { id:7,  pairId:4,  type:"vivant",      name:"LIBELLULE",                  tagline:"Je vole sur place avec 4 ailes indépendantes.",
    photo: BASE + "card_7.png",
    explication:{ titre:"Libellule & Micro-Drone", texte:"La libellule contrôle chacune de ses 4 ailes indépendamment, permettant vol stationnaire et 54 km/h. Ce mécanisme a inspiré les micro-drones ultra-manœuvrables." }},
  { id:8,  pairId:4,  type:"application", name:"MICRO-DRONE",                tagline:"Je filme le ciel avec une agilité d'insecte.",
    photo: BASE + "card_8.png",
    explication:null },

  { id:9,  pairId:5,  type:"vivant",      name:"ARAIGNÉE",                   tagline:"Mon fil est plus résistant que l'acier.",
    photo: BASE + "card_9.png",
    explication:{ titre:"Araignée & Fibre Bio-synthétique", texte:"La soie d'araignée est 5× plus résistante que l'acier à poids égal, extensible et biodégradable. Ce principe inspire des fibres pour la médecine et le blindage léger." }},
  { id:10, pairId:5,  type:"application", name:"FIBRE BIO-SYNTHÉTIQUE",      tagline:"Un fil souple mais impossible à casser.",
    photo: BASE + "card_10.png",
    explication:null },

  { id:11, pairId:6,  type:"vivant",      name:"MOUSTIQUE",                  tagline:"Je pique sans que tu ne sentes rien.",
    photo: BASE + "card_11.png",
    explication:{ titre:"Moustique & Aiguille indolore", texte:"L'aiguille du moustique est composée de 6 lames microscopiques qui s'insèrent graduellement, supprimant la douleur. Des ingénieurs l'ont reproduite pour des aiguilles médicales quasi-indolores." }},
  { id:12, pairId:6,  type:"application", name:"AIGUILLE INDOLORE",          tagline:"Soigner sans douleur, c'est possible.",
    photo: BASE + "card_12.png",
    explication:null },

  { id:13, pairId:7,  type:"vivant",      name:"SCARABÉE STENOCARA",         tagline:"Je capture l'eau sur mes bosses hydrophiles.",
    photo: BASE + "card_13.png",
    explication:{ titre:"Scarabée Stenocara & Filet Capteur de Rosée", texte:"Ce scarabée du Namib capte l'humidité grâce à des micro-bosses. Ce principe inspire des filets qui récoltent de l'eau potable dans les zones arides." }},
  { id:14, pairId:7,  type:"application", name:"FILET CAPTEUR DE ROSÉE",     tagline:"Je crée de l'eau potable à partir de la brume.",
    photo: BASE + "card_14.png",
    explication:null },

  { id:15, pairId:8,  type:"vivant",      name:"MANCHOT EMPEREUR",           tagline:"En groupe, nous créons un bouclier thermique.",
    photo: BASE + "card_15.png",
    explication:{ titre:"Manchot & Isolation thermique collective", texte:"Les manchots se regroupent en formations tournantes, maintenant une température constante. Ce principe inspire des architectures d'isolation collective passive." }},
  { id:16, pairId:8,  type:"application", name:"ISOLATION THERMIQUE",        tagline:"L'architecture du vivant au service du bâtiment.",
    photo: BASE + "card_16.png",
    explication:null },

  { id:17, pairId:9,  type:"vivant",      name:"FLEUR DE LOTUS",             tagline:"L'eau perle sur moi sans me mouiller.",
    photo: BASE + "card_17.png",
    explication:{ titre:"Lotus & Peinture Autonettoyante", texte:"La surface du lotus est couverte de nano-picots qui empêchent eau et saleté d'adhérer. Ce principe a inspiré des peintures et textiles autonettoyants utilisés en architecture." }},
  { id:18, pairId:9,  type:"application", name:"PEINTURE AUTONETTOYANTE",    tagline:"La saleté glisse sur moi comme sur un lotus.",
    photo: BASE + "card_18.png",
    explication:null },

  { id:19, pairId:10, type:"vivant",      name:"PIEUVRE",                    tagline:"Je change de couleur en un instant.",
    photo: BASE + "card_19.png",
    explication:{ titre:"Pieuvre & Camouflage Adaptatif", texte:"La pieuvre contrôle des milliers de chromatophores pour se fondre instantanément. Ce principe inspire des matériaux adaptatifs utilisés en défense et en architecture." }},
  { id:20, pairId:10, type:"application", name:"CAMOUFLAGE ADAPTATIF",       tagline:"Je change d'apparence selon mon environnement.",
    photo: BASE + "card_20.png",
    explication:null },

  { id:21, pairId:11, type:"vivant",      name:"TERMITIÈRE",                 tagline:"Mon terrier reste frais malgré la chaleur.",
    photo: BASE + "card_21.png",
    explication:{ titre:"Termitière & Ventilation Naturelle", texte:"Les termitières maintiennent une température constante grâce à un réseau de cheminées. Mick Pearce s'en est inspiré pour le centre commercial Eastgate au Zimbabwe, sans climatisation." }},
  { id:22, pairId:11, type:"application", name:"VENTILATION NATURELLE",      tagline:"Rafraîchir sans climatisation, c'est possible.",
    photo: BASE + "card_22.png",
    explication:null },

  { id:23, pairId:12, type:"vivant",      name:"GECKO",                      tagline:"Je grimpe au plafond sans colle ni ventouse.",
    photo: BASE + "card_23.png",
    explication:{ titre:"Gecko & Adhésif Nano-structuré", texte:"Les pattes du gecko sont couvertes de millions de nano-poils créant des forces de Van der Waals. Ce principe a inspiré des adhésifs réutilisables pour la robotique et la médecine." }},
  { id:24, pairId:12, type:"application", name:"ADHÉSIF NANO-STRUCTURÉ",     tagline:"Colle sans colle, tient sans ventouse.",
    photo: BASE + "card_24.png",
    explication:null },

  { id:25, pairId:13, type:"vivant",      name:"CACTUS",                     tagline:"Je capte chaque goutte d'eau dans le désert.",
    photo: BASE + "card_25.png",
    explication:{ titre:"Cactus & Collecte d'Eau Atmosphérique", texte:"Les épines du cactus ont une forme conique qui dirige les gouttelettes vers la base. Ce principe inspire des systèmes de collecte d'eau dans les zones arides." }},
  { id:26, pairId:13, type:"application", name:"COLLECTE D'EAU ATMOSPHÉRIQUE", tagline:"Extraire l'eau de l'air, même dans le désert.",
    photo: BASE + "card_26.png",
    explication:null },

  { id:27, pairId:14, type:"vivant",      name:"ABEILLE",                    tagline:"Mes alvéoles sont la structure la plus efficace.",
    photo: BASE + "card_27.png",
    explication:{ titre:"Ruche & Structure Alvéolaire", texte:"Les alvéoles hexagonales maximisent le volume tout en minimisant la cire. Cette géométrie inspire des matériaux ultra-légers et résistants en aéronautique et architecture." }},
  { id:28, pairId:14, type:"application", name:"STRUCTURE ALVÉOLAIRE",       tagline:"Léger, résistant, efficace — comme une ruche.",
    photo: BASE + "card_28.png",
    explication:null },

  { id:29, pairId:15, type:"vivant",      name:"DAUPHIN",                    tagline:"Mon sonar perçoit ce que les yeux ne voient pas.",
    photo: BASE + "card_29.png",
    explication:{ titre:"Dauphin & Échographie Médicale", texte:"Les dauphins émettent des ultrasons et interprètent les échos. Ce principe a inspiré l'échographie médicale, permettant de visualiser l'intérieur du corps sans chirurgie." }},
  { id:30, pairId:15, type:"application", name:"ÉCHOGRAPHIE MÉDICALE",       tagline:"Voir l'invisible grâce aux ultrasons.",
    photo: BASE + "card_30.png",
    explication:null },

  { id:31, pairId:16, type:"vivant",      name:"OS HUMAIN",                  tagline:"Je suis vide mais impossible à briser.",
    photo: BASE + "card_31.png",
    explication:{ titre:"Os humain & Tour Eiffel", texte:"Gustave Eiffel s'est inspiré de la structure interne du fémur — des travées creuses — pour concevoir la Tour Eiffel. Résistance maximale avec un minimum de matière." }},
  { id:32, pairId:16, type:"application", name:"TOUR EIFFEL",                tagline:"Une dentelle de fer inspirée par un fémur.",
    photo: BASE + "card_32.png",
    explication:null },

  { id:33, pairId:17, type:"vivant",      name:"PLUMES DE CHOUETTE",         tagline:"Je vole dans un silence absolu.",
    photo: BASE + "card_33.png",
    explication:{ titre:"Chouette & Éolienne Silencieuse", texte:"Les plumes de chouette ont des bords dentelés qui brisent les turbulences, éliminant le bruit. Ce principe est appliqué aux lames d'éoliennes pour réduire le bruit." }},
  { id:34, pairId:17, type:"application", name:"ÉOLIENNE SILENCIEUSE",       tagline:"De l'énergie sans le bruit.",
    photo: BASE + "card_34.png",
    explication:null },

  { id:35, pairId:18, type:"vivant",      name:"CORAIL",                     tagline:"Je construis des récifs en absorbant le CO₂.",
    photo: BASE + "card_35.png",
    explication:{ titre:"Corail & Béton Biosourcé", texte:"Le corail calcifie le CO₂ dissous pour construire ses récifs. Ce principe inspire un béton nouvelle génération qui capture le carbone au lieu d'en émettre." }},
  { id:36, pairId:18, type:"application", name:"BÉTON BIOSOURCÉ",            tagline:"Construire en capturant le carbone.",
    photo: BASE + "card_36.png",
    explication:null },

  { id:37, pairId:19, type:"vivant",      name:"LUCIOLE",                    tagline:"Je produis de la lumière froide sans gaspiller.",
    photo: BASE + "card_37.png",
    explication:{ titre:"Luciole & Ampoule LED", texte:"La luciole produit de la lumière par bioluminescence — une réaction sans chaleur. Ce principe a inspiré les LEDs modernes qui convertissent 90 % de l'énergie en lumière." }},
  { id:38, pairId:19, type:"application", name:"AMPOULE LED",                tagline:"La lumière froide de la luciole reproduite.",
    photo: BASE + "card_38.png",
    explication:null },

  { id:39, pairId:20, type:"vivant",      name:"SÉQUOIA",                    tagline:"Je capte la brume avec mes feuilles.",
    photo: BASE + "card_39.png",
    explication:{ titre:"Séquoia & Toiture Récoltante", texte:"Les feuilles du séquoia capturent la brume côtière par condensation. Ce principe inspire des toitures et façades qui récoltent l'eau atmosphérique dans les zones sèches." }},
  { id:40, pairId:20, type:"application", name:"TOITURE RÉCOLTANTE",         tagline:"Capter l'eau du ciel sans pluie.",
    photo: BASE + "card_40.png",
    explication:null },

  { id:41, pairId:21, type:"vivant",      name:"NAGEOIRE DE REQUIN",         tagline:"Ma forme me propulse sans effort.",
    photo: BASE + "card_41.png",
    explication:{ titre:"Nageoire de Requin & Coque de Bateau", texte:"La forme en V des nageoires du requin réduit la résistance de l'eau. Ce principe inspire la conception de coques de bateaux et sous-marins plus économes." }},
  { id:42, pairId:21, type:"application", name:"COQUE DE BATEAU",            tagline:"Fendre l'eau comme un requin.",
    photo: BASE + "card_42.png",
    explication:null },

  { id:43, pairId:22, type:"vivant",      name:"POISSON COFFRE",             tagline:"Ma forme carrée est paradoxalement aérodynamique.",
    photo: BASE + "card_43.png",
    explication:{ titre:"Poisson Coffre & Concept Car Bionic", texte:"Le poisson coffre, malgré sa forme cubique, est très aérodynamique. Mercedes s'en est inspiré pour le Concept Car Bionic, réduisant la résistance à l'air de 65 %." }},
  { id:44, pairId:22, type:"application", name:"CONCEPT CAR BIONIC",         tagline:"Une voiture inspirée d'un poisson cubique.",
    photo: BASE + "card_44.png",
    explication:null },

  { id:45, pairId:23, type:"vivant",      name:"GECKO (ADHÉRENCE)",          tagline:"Je grimpe sur n'importe quelle surface.",
    photo: BASE + "card_45.png",
    explication:{ titre:"Gecko & Robot Grimpeur", texte:"Les millions de nano-poils des pattes du gecko créent une adhérence sans colle. Ce principe inspire des robots capables de grimper sur des surfaces verticales lisses." }},
  { id:46, pairId:23, type:"application", name:"ROBOT GRIMPEUR",             tagline:"Grimper sans colle, comme un gecko.",
    photo: BASE + "card_46.png",
    explication:null },

  { id:47, pairId:24, type:"vivant",      name:"FEUILLE D'ÉRABLE",           tagline:"Je vole en tournant pour atterrir doucement.",
    photo: BASE + "card_47.png",
    explication:{ titre:"Graine d'Érable & Drone Mono-aile", texte:"La graine d'érable (samara) tourne en spirale pour ralentir sa chute. Ce mécanisme a inspiré des micro-drones mono-aile capables de planer avec peu d'énergie." }},
  { id:48, pairId:24, type:"application", name:"DRONE MONO-AILE",            tagline:"Planer longtemps avec une seule aile.",
    photo: BASE + "card_48.png",
    explication:null },

  { id:49, pairId:25, type:"vivant",      name:"MANTE RELIGIEUSE",           tagline:"Je frappe plus vite que l'œil ne peut voir.",
    photo: BASE + "card_49.png",
    explication:{ titre:"Mante Religieuse & Bras Chirurgical", texte:"La mante frappe à 10 000 g d'accélération avec une précision millimétrique. Cette biomécanique inspire les bras robotiques chirurgicaux ultra-précis." }},
  { id:50, pairId:25, type:"application", name:"BRAS CHIRURGICAL",           tagline:"La précision de la mante au service de la chirurgie.",
    photo: BASE + "card_50.png",
    explication:null },
];

const INDICES_DATA = [
  { id:1,  pairId:1,  titre:"La Termitière", texte:"Cet oiseau plonge sans éclaboussures... comme un train qui traverse un tunnel.", cout:20 },
  { id:2,  pairId:2,  titre:"Effet Lotus",   texte:"Les bosses sur ses nageoires la rendent plus efficace dans l'eau... et dans l'air ?", cout:20 },
  { id:3,  pairId:3,  titre:"Peau de Requin",texte:"La peau de ce prédateur réduit la friction à grande vitesse.", cout:35 },
  { id:4,  pairId:4,  titre:"Ailes de Libellule", texte:"4 ailes indépendantes = 4 moteurs. La nature a inventé les drones bien avant.", cout:50 },
  { id:5,  pairId:5,  titre:"Fil d'Araignée",texte:"La nature a créé le matériau le plus résistant bien avant les laboratoires.", cout:15 },
  { id:6,  pairId:6,  titre:"Aiguille de Moustique", texte:"6 lames qui s'insèrent graduellement. Plus fin qu'une seringue.", cout:50 },
  { id:7,  pairId:7,  titre:"Collecte Scarabée", texte:"Dans le désert, l'eau se condense. Comment la capturer ?", cout:35 },
  { id:8,  pairId:8,  titre:"Formation Manchots", texte:"La chaleur partagée est la chaleur conservée.", cout:20 },
  { id:9,  pairId:9,  titre:"Effet Hydrophobe", texte:"L'eau perle sur cette fleur sans jamais l'humecter.", cout:35 },
  { id:10, pairId:10, titre:"Camouflage Pieuvre", texte:"En quelques millisecondes, elle disparaît visuellement.", cout:50 },
  { id:11, pairId:11, titre:"Ventilation Termites", texte:"Un bâtiment qui respire comme une termitière. Il existe au Zimbabwe.", cout:200 },
  { id:12, pairId:12, titre:"Adhérence Gecko", texte:"Millions de nano-poils. Aucune colle. Pourtant ça tient au plafond.", cout:50 },
  { id:13, pairId:13, titre:"Épines de Cactus", texte:"Ses épines en forme de cône orientent chaque goutte vers la base.", cout:35 },
  { id:14, pairId:14, titre:"Toit de Corail", texte:"L'hexagone : la forme qui maximise le volume en minimisant la matière.", cout:20 },
  { id:15, pairId:15, titre:"Sonar Dauphin", texte:"Il voit sans lumière. Ses ondes traversent la chair.", cout:50 },
  { id:16, pairId:16, titre:"Structure Osseuse", texte:"Creux mais incassable. Gustave Eiffel l'a vu dans un fémur.", cout:15 },
  { id:17, pairId:17, titre:"Plumes Silencieuses", texte:"Son vol est silencieux grâce à ses bords dentelés.", cout:35 },
  { id:18, pairId:18, titre:"Calcification Corail", texte:"Il absorbe le CO₂ pour construire. Un béton fait pareil.", cout:50 },
  { id:19, pairId:19, titre:"Bioluminescence", texte:"Elle produit de la lumière sans chaleur. 0% de gaspillage.", cout:20 },
  { id:20, pairId:20, titre:"Biocapacité Totale", texte:"Il capte la brume avec ses feuilles. Une toiture peut faire pareil.", cout:200 },
  { id:21, pairId:21, titre:"Hydrodynamique", texte:"Sa forme en V fend l'eau avec un minimum de résistance.", cout:35 },
  { id:22, pairId:22, titre:"Aérodynamique Cube", texte:"Carré mais aérodynamique. Mercedes y a cru.", cout:50 },
  { id:23, pairId:23, titre:"Nano-adhérence", texte:"Il grimpe au plafond grâce à des millions de nano-poils.", cout:20 },
  { id:24, pairId:24, titre:"Rotation Samara", texte:"Elle tourne en spirale pour ralentir. Un drone fait pareil.", cout:35 },
  { id:25, pairId:25, titre:"Frappe Éclair", texte:"10 000 g d'accélération, précision millimétrique. Un bras robot l'imite.", cout:50 },
];

const REGLES_DATA = {
  objectif: "Associer chaque élément du vivant à l'application humaine qui s'en inspire. Devenez un expert en observant les ingéniosités de la nature pour résoudre nos défis technologiques actuels.",
  etapes: [
    "Toutes les cartes sont visibles sur le plateau dès le début de la partie.",
    "Cliquez sur une carte Vivant (bordure verte) puis une carte Application (bordure bleue).",
    "Si la paire est correcte : une explication détaillée apparaît et vous gagnez de l'XP !",
    "Si c'est incorrect : les cartes se signalent en rouge et restent disponibles pour un nouvel essai."
  ],
  xp: "Vous gagnez 100 XP par paire correcte trouvée. Dépensez vos XP dans l'inventaire pour acheter des indices (50 XP chacun).",
  indices: "Un indice vous donne un coup de pouce sur une paire non encore trouvée. Achetez-les dans l'onglet Indices."
};
